### ISSUE TITLE
UnboundLocalError: local variable 'price' referenced before assignment

### ISSUE THREAD

**Issue by Methodise** [xeroc/stakemachine#15]
2017-10-21 23:52:28,260 INFO Replacing orders
2017-10-21 23:52:28,467 CRITICAL Error in on_market: 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/bot.py", line 85, in on_market
    self.bots[botname].onMarketUpdate(data)
  File "/home/stakemachine/.local/lib/python3.5/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 114, in test
    self.updateorders()
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 45, in updateorders
    price = self.getprice()
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 90, in getprice
    return price
UnboundLocalError: local variable 'price' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/bitshares-0.1.8-py3.5.egg/bitsharesapi/websocket.py", line 270, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/usr/local/lib/python3.5/dist-packages/bitshares-0.1.8-py3.5.egg/bitsharesapi/websocket.py", line 270, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/stakemachine/.local/lib/python3.5/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/bitshares-0.1.8-py3.5.egg/bitshares/notify.py", line 142, in process_market
    self.on_market(Order(i))
  File "/home/stakemachine/.local/lib/python3.5/site-packages/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/bot.py", line 87, in on_market
    self.bots[botname].error_onMarketUpdate(e)
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 33, in error
    pprint(self.execute())
  File "/usr/local/lib/python3.5/dist-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/basestrategy.py", line 164, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/usr/local/lib/python3.5/dist-packages/bitshares-0.1.8-py3.5.egg/bitshares/transactionbuilder.py", line 176, in broadcast
    self.sign()
  File "/usr/local/lib/python3.5/dist-packages/bitshares-0.1.8-py3.5.egg/bitshares/transactionbuilder.py", line 156, in sign
    raise MissingKeyError
bitshares.exceptions.MissingKeyError

**Comment by Methodise** [comment]
My config was merely insufficient. It might be worth fleshing out config.yaml with more clues for the likes of me.
