### ISSUE TITLE
CRITICAL Error in on_block

### ISSUE THREAD

**Issue by maxyc** [xeroc/stakemachine#17]
```
vagrant@debian9:/var/www/bots/stakemachine$ stakemachine  --configfile config.yml  run
Current Wallet Passphrase: 
2017-12-13 11:04:29,405 INFO Replacing orders
2017-12-13 11:04:32,085 CRITICAL Error in on_block: 

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/bot.py", line 66, in on_block
    self.bots[botname].ontick(data)
  File "/home/vagrant/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 97, in tick
    self.test()
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 114, in test
    self.updateorders()
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 78, in updateorders
    pprint(self.execute())
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/basestrategy.py", line 164, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/home/vagrant/.local/lib/python3.5/site-packages/bitshares-0.1.8-py3.5.egg/bitshares/transactionbuilder.py", line 176, in broadcast
    self.sign()
  File "/home/vagrant/.local/lib/python3.5/site-packages/bitshares-0.1.8-py3.5.egg/bitshares/transactionbuilder.py", line 156, in sign
    raise MissingKeyError
bitshares.exceptions.MissingKeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.5/site-packages/bitshares-0.1.8-py3.5.egg/bitsharesapi/websocket.py", line 270, in on_message
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/vagrant/.local/lib/python3.5/site-packages/bitshares-0.1.8-py3.5.egg/bitsharesapi/websocket.py", line 270, in <listcomp>
    [getattr(self.events, callbackname)(x) for x in data["params"][1]]
  File "/home/vagrant/.local/lib/python3.5/site-packages/Events-0.3-py3.5.egg/events/events.py", line 95, in __call__
    f(*a, **kw)
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/bot.py", line 68, in on_block
    self.bots[botname].error_ontick(e)
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/strategies/walls.py", line 33, in error
    pprint(self.execute())
  File "/home/vagrant/.local/lib/python3.5/site-packages/stakemachine-0.0.6-py3.5.egg/stakemachine/basestrategy.py", line 164, in execute
    r = self.bitshares.txbuffer.broadcast()
  File "/home/vagrant/.local/lib/python3.5/site-packages/bitshares-0.1.8-py3.5.egg/bitshares/transactionbuilder.py", line 176, in broadcast
    self.sign()
  File "/home/vagrant/.local/lib/python3.5/site-packages/bitshares-0.1.8-py3.5.egg/bitshares/transactionbuilder.py", line 156, in sign
    raise MissingKeyError
bitshares.exceptions.MissingKeyError

2017-12-13 11:04:46,950 INFO The bot Walls has been disabled
```

**Comment by maxyc** [comment]
```
node: "wss://bitshares.openledger.info/ws"
prefix: "BTS"
safe_mode: True
account: "maxyc-webber-test"
wif: ""
market_separator: ":"
bots:
        Walls:
             module: stakemachine.strategies.walls
             bot: Walls
             market: USD:BTS
             account: maxyc-webber-test
             bundle: True
             test:
                     blocks: 10
             target:
                     reference: feed
                     offsets:
                         buy: 2.5
                         sell: 2.5
                     amount:
                         buy: 5.0
                         sell: 5.0
             threshold: 2
```
