### ISSUE TITLE
error :  No module named 'autobahn'

### ISSUE THREAD

**Issue by bue-twitter** [xeroc/stakemachine#8]
No module named 'autobahn'

```
xem@xem:~/uti/stakemachine$ stakemachine -c config-example.yml once
Traceback (most recent call last):
  File "/home/xem/.local/lib/python3.5/site-packages/graphenelib-0.4.4-py3.5.egg/grapheneapi/graphenewsprotocol.py", line 9, in <module>
ImportError: No module named 'autobahn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xem/.local/bin/stakemachine", line 11, in <module>
    load_entry_point('stakemachine==0.0.1', 'console_scripts', 'stakemachine')()
  File "/home/xem/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/xem/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2621, in load_entry_point
    return ep.load()
  File "/home/xem/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2281, in load
    return self.resolve()
  File "/home/xem/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2287, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/xem/.local/lib/python3.5/site-packages/stakemachine-0.0.1-py3.5.egg/stakemachine/__main__.py", line 9, in <module>
  File "/home/xem/.local/lib/python3.5/site-packages/stakemachine-0.0.1-py3.5.egg/stakemachine/bot.py", line 1, in <module>
  File "/home/xem/.local/lib/python3.5/site-packages/graphenelib-0.4.4-py3.5.egg/grapheneapi/graphenewsprotocol.py", line 11, in <module>
ImportError: Missing dependency 'autobahn'.
```

**Comment by bue-twitter** [comment]
try following to fix above problem 

`pip3 install autobahn`
